spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        repositories:
          bootstrap-mode: deferred
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - ${REDIS_SENTINEL_1:redis-sentinel-1}:${REDIS_SENTINEL_PORT_1:26379}
          - ${REDIS_SENTINEL_2:redis-sentinel-2}:${REDIS_SENTINEL_PORT_2:26379}
          - ${REDIS_SENTINEL_3:redis-sentinel-3}:${REDIS_SENTINEL_PORT_3:26379}
      repositories:
        enabled: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${OTEL_COLLECTOR_HOST:localhost}:${OTEL_COLLECTOR_PORT:4328}/v1/traces

logging:
  file:
    name: logs/user.log
  level:
    root: INFO
    com.project.userservice: INFO
    com.project.userservice.infrastructure.filter: INFO

jwt:
  secret-key: ${JWT_SECRET_KEY}
