server:
  port: 8087

spring:
  application:
    name: delivery-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3314/delivery_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USER:chaeuser}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${OTEL_COLLECTOR_HOST:localhost}:${OTEL_COLLECTOR_PORT:4328}/v1/traces

logging:
  file:
    name: logs/delivery.log
  level:
    root: INFO
    com.project.deliveryservice: INFO
