spring:
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USER}
    password: ${DB_DEV_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: all
#      retries: 3
#      properties:
#        enable.idempotence: true
#        max.in.flight.requests.per.connection: 5
#    consumer:
#      group-id: inventory-service-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.project.chaechaeserver.domain.event"
#        spring.json.type.mapping: "event:com.project.chaechaeserver.domain.event.InventoryEvent"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

springdoc:
  use-fqn: true

chatbot:
  base-url:
    fast-api: http://127.0.0.1:8000

logging:
  level:
    com.project.chaechaeserver.application.global.aspect: INFO
    com.project.chaechaeserver.domain.service.inventory: INFO